GET http://localhost:8080/pair HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDFlOWMzYzcyNzIwY2M4YmVkYmQ0MSIsImlhdCI6MTczMjM4NDk0OSwiZXhwIjoxNzMyMzg4NTQ5fQ.9yYKvbw5zuJUWTNEfVnhIFPjPGM4kd8YbgXHY8pyeZQ